### ISSUE TITLE
TWBaseType missing STATEFORMATTING and TWWidgetProperties missing defaultBindingTargetProperty

### ISSUE THREAD

**Issue by jmccuen** [stefan-lacatus/ThingworxWidgetSupportPackage#1]
As said in the title, the TWBaseType interface is missing the item 'STATEFORMATTING ', which is used to define state formatting widget properties, and the TWWidgetProperties  interface is missing defaultBindingTargetProperty?: string; which would allow you to set a default binding target for the widget. I wasn't able to submit a pull request with these minor changes.

**Comment by stefan-lacatus** [comment]
Fixed in 4f87703fb384821c71159c917a19ce839eebdd0f and 19dab7640dc8fccb360561a97f51ebd6e56e17bc.
You'll have to run `npm update typescriptwebpacksupport` to install the latest updates
