### ISSUE TITLE
Support of customEditor?

### ISSUE THREAD

**Issue by atondorf** [stefan-lacatus/ThingworxWidgetSupportPackage#17]
Support of customEditors would be Great!
Official documentation for WidgetDevelopment also only mentiones this very roughly.
https://support.ptc.com/help/thingworx/platform/r9/en/#page/ThingWorx/Help/Best_Practices_for_Developing_Applications/visualization_WidgetApiMashupBuilder.html#

**Comment by stefan-lacatus** [comment]
Support for custom editors already exists, but it has to play by the ThingWorx rules. So, you can add the two following annotations to your widget: 
```js
@description('A widget')
@TWWidgetDefinition('Test', autoResizable, customEditor('MyDialogName'), customEditorMenuText('Open my config'))
class MyWidget extends TWComposerWidget {

}
```

Then, you would have add on `TW.IDE.Dialogs` a new key `TW.IDE.Dialogs.MyDialogName`.

Take a look at the existing keys in that global object for reference.

An other alternative is to override these two methods on the widget https://github.com/ptc-iot-sharing/ThingworxWidgetSupportPackage/blob/supportv2/types/index.d.ts#L959-L970, as they would allow for more actions in that context menu

**Comment by stefan-lacatus** [comment]
Closing this as it seems like a resolved issue. Let me know if you have any other questions.
