### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by JayT9000** [stefan-lacatus/ThingworxWidgetSupportPackage#6]
Hello,
we created a thingworx widget with the ThingworxDemoWebpackWidget package and get an error in IE11. 

![image](https://user-images.githubusercontent.com/52569417/73660584-c27a7500-4698-11ea-8bee-eba650b6763f.png)

The error occurs while loading the widgetRuntimeSupport.js in the CombinedExtention.XXX.js.
![image](https://user-images.githubusercontent.com/52569417/73660685-f48bd700-4698-11ea-8ca9-0ab7c557bb97.png)

Has anybody an idea how to fix this?

Best regards
Jan

**Comment by BogdanMihaiciuc** [comment]
This project uses newer javascript features such as async/await, classes and others which are not supported in IE11 unless transpiled.

When you package and install the widget in development mode, transpilation will not occur so you will get a syntax error since IE11 doesn't understand the newer javascript syntax features.

Consider testing in IE11 using the production build.

**Comment by JayT9000** [comment]
The production code also run into a syntax error in IE11 because of the class statement which isn't supported in IE.
![image](https://user-images.githubusercontent.com/52569417/73743408-bd77fd00-474e-11ea-8a80-853ebb82ced1.png)

**Comment by BogdanMihaiciuc** [comment]
I just checked and it looks like the transpiler skips external modules.

In your webpack config, you can disable this by removing the exclude property from the babel loader:

![Screenshot 2020-02-04 at 15 07 27](https://user-images.githubusercontent.com/41421247/73747422-12703f00-4760-11ea-85c5-e59c17f6a281.png)

I am not sure whether this would cause issues, but it's worth trying.

**Comment by JayT9000** [comment]
This solve the problem with the class statement but the widget won't be initialized in IE and no error message appears in the console. I went a step backwards and checked out the ptc-iot-sharing/ThingworxDemoWebpackWidget to ensure that's not my implementation which fails in IE. 
I'm pretty sure widgets based on ptc-iot-sharing/ThingworxDemoWebpackWidget are currently not runable in IE. The widgets aren't part of the TW.Runtime.Widgets namespace.
 
![image](https://user-images.githubusercontent.com/52569417/73753909-bdcec300-4763-11ea-8fdb-d7dd87a18dec.png)

Shall I open an issue in ThingworxDemoWebpackWidget?

**Comment by BogdanMihaiciuc** [comment]
Add `"@babel/polyfill"` as a runtime dependency and include it in the entry point.

![Screenshot 2020-02-05 at 11 51 57](https://user-images.githubusercontent.com/41421247/73830831-f75c0880-480d-11ea-9b1f-cba8300d8528.png)

Note that this will add some 4000 lines of code to your widget to support missing javascript features in IE 11. I'm not sure that we'll roll these changes into the project considering that the latest version of Thingworx (8.5) no longer supports IE 11 either.

**Comment by JayT9000** [comment]
This causes in an other problem because the redefine of "includes"-property through the polyfill throw an error at runtime. I think your right, it doesn't make sense to invest to much time because of the end of support for IE in Thingworx 8.5.

Thank you very much for your support!
